[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_extensions
prompt = no

[req_distinguished_name]
CN = OpenSK Apple Authenticator

[v3_extensions]
# 核心：注入 Apple ID 严格检测的 FIDO 传输 OID (USB+NFC)
1.3.6.1.4.1.45724.2.1.1 = ASN1:BITSTRING:0x03
